AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  sam-test-2

Parameters:
  Stage:
    Type: String
    Description: Stage to deploy resources to
    AllowedValues:
      - dev
      - staging
      - production


Conditions:
  IsProduction: !Equals [ !Ref Stage, production ]



Globals:
  Api:
    OpenApiVersion: 3.0.1 
  Function:
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 5
    Tracing: Active
    Tags:
      environment: !Ref Stage

Resources:
  ModelHandelerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: dist/
      Handler: app.modelHandler
      Events:
        ModelPostAPI:
          Type: Api
          Properties:
            Path: /model/{modelName}
            Method: POST
        ModelGetAPI:
          Type: Api
          Properties:
            Path: /model/{modelName}/{modelId}
            Method: GET 

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
